export const DANG_NHAP_BAT_DAU = "DANG_NHAP_BAT_DAU";
export const DANG_NHAP_THANH_CONG = "DANG_NHAP_THANH_CONG";
export const DANG_NHAP_THAT_BAI = "DANG_NHAP_THAT_BAI";

export const TRUY_CAP_VALID_CODE_BAT_DAU = "TRUY_CAP_VALID_CODE_BAT_DAU";
export const TRUY_CAP_VALID_CODE_THANH_CONG = "TRUY_CAP_VALID_CODE_THANH_CONG";
export const TRUY_CAP_VALID_CODE_THAT_BAI = "TRUY_CAP_VALID_CODE_THAT_BAI";

export const TRUY_CAP_LOGIN_TK88_BAT_DAU = "TRUY_CAP_LOGIN_TK88_BAT_DAU";
export const TRUY_CAP_LOGIN_TK88_THANH_CONG = "TRUY_CAP_LOGIN_TK88_THANH_CONG";
export const TRUY_CAP_LOGIN_TK88_THAT_BAI = "TRUY_CAP_LOGIN_TK88_THAT_BAI";
export const TRUY_CAP_THONG_TIN_NGUOI_DUNG_BAT_DAU =
  "TRUY_CAP_THONG_TIN_NGUOI_DUNG_BAT_DAU";
export const TRUY_CAP_THONG_TIN_NGUOI_DUNG_THANH_CONG =
  "TRUY_CAP_THONG_TIN_NGUOI_DUNG_THANH_CONG";
export const TRUY_CAP_THONG_TIN_NGUOI_DUNG_THAT_BAI =
  "TRUY_CAP_THONG_TIN_NGUOI_DUNG_THAT_BAI";
export const XU_LY_BET_BAT_DAU = "XU_LY_BET_BAT_DAU";
export const XU_LY_BET_THANH_CONG = "XU_LY_BET_THANH_CONG";
export const XU_LY_BET_THAT_BAI = "XU_LY_BET_THAT_BAI";

export const TRUY_CAP_DS_BOT_BAT_DAU = "TRUY_CAP_DS_BOT_BAT_DAU";
export const TRUY_CAP_DS_BOT_THANH_CONG = "TRUY_CAP_DS_BOT_THANH_CONG";
export const TRUY_CAP_DS_BOT_THAT_BAI = "TRUY_CAP_DS_BOT_THAT_BAI";
export const START_BOT_BAT_DAU = "START_BOT_BAT_DAU";
export const START_BOT_THANH_CONG = "START_BOT_THANH_CONG";
export const START_BOT_THAT_BAI = "START_BOT_THAT_BAI";
export const CHOI_THU_BAT_DAU = "CHOI_THU_BAT_DAU";
export const CHOI_THU_THANH_CONG = "CHOI_THU_THANH_CONG";
export const CHOI_THU_THAT_BAI = "CHOI_THU_THAT_BAI";
export const TRUY_CAP_DS_BET_BAT_DAU = "TRUY_CAP_DS_BET_BAT_DAU";
export const TRUY_CAP_DS_BET_THANH_CONG = "TRUY_CAP_DS_BET_THANH_CONG";
export const TRUY_CAP_DS_BET_THAT_BAI = "TRUY_CAP_DS_BET_THAT_BAI";
export const XU_LY_XOA_BOT_BAT_DAU = "XU_LY_XOA_BOT_BAT_DAU";
export const XU_LY_XOA_BOT_THANH_CONG = "XU_LY_XOA_BOT_THANH_CONG";
export const XU_LY_XOA_BOT_THAT_BAI = "XU_LY_XOA_BOT_THAT_BAI";
export const DANG_KY_BAT_DAU = "DANG_KY_BAT_DAU";
export const DANG_KY_THANH_CONG = "DANG_KY_THANH_CONG";
export const DANG_KY_THAT_BAI = "DANG_KY_THAT_BAI";
export const DANG_XUAT_BAT_DAU = "DANG_XUAT_BAT_DAU";
export const DANG_XUAT_THANH_CONG = "DANG_XUAT_THANH_CONG";
export const DANG_XUAT_THAT_BAI = "DANG_XUAT_THAT_BAI";

export const XU_LY_NGUNG_BOT_BAT_DAU = "XU_LY_NGUNG_BOT_BAT_DAU";
export const XU_LY_NGUNG_BOT_THANH_CONG = "XU_LY_NGUNG_BOT_THANH_CONG";
export const XU_LY_NGUNG_BOT_THAT_BAI = "XU_LY_NGUNG_BOT_THAT_BAI";
export const CAP_NHAT_TOKEN_88_BAT_DAU = "CAP_NHAT_TOKEN_88_BAT_DAU";
export const CAP_NHAT_TOKEN_88_THANH_CONG = "CAP_NHAT_TOKEN_88_THANH_CONG";
export const CAP_NHAT_TOKEN_88_THAT_BAI = "CAP_NHAT_TOKEN_88_THAT_BAI";
